title: Ziyue Wang
email: ziyue.wang0125@gmail.com
description: Personal site for Ziyue Wang
baseurl: ""
url: "https://VincentWang25.github.io"
github_username:  VincentWang25

markdown: kramdown
remote_theme: jekyll/minima
google_analytics: G-6SRK9DNEMH

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme